version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
branches:
  only:
    - master
build_script:
  - ps: .\Build\build.ps1 -Script Build/build.cake
test: off
deploy: off
environment:
  CODECOV_TOKEN:
    secure: JaL0l4hEGxSMrLLaso/UmV33DSGWGwMR+aL382cik8NSi1iB93TjFomgOHD/LTmb