//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersianFaker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Name {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Name() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersianFaker.Resources.Name", typeof(Name).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبتین;آتش;آترین;آتورپات;آذرخش;آذرمه;آذین;آرتین;آرام;آراد;آرتا;آرش;آرشام;آرمان;آرمین;آریا;آریابان;آریانا;آرین;آریوبرزن;آزاد;آزرمگان;آساد;آستیاژ;آستیاگ;آوه;آویژه;آیین‌گشسب;آریو;آریافر;آریامن;آریامنش;آریامهر;آریان;اخگر;اُرُد;اردشیر;اردلان;اردوان;ارژنگ;ارس;ارشا;الیاس;اَرَشک;ارمایل;اروند;اژدر;اسفندیار;اشک;اشکان;اشکبوس;افراسیاب;افشین;البرز;الوند;امید;انوش;انوشیروان;اورمزد;اورنگ;ایرج;ایشتوویگو;بابک;باربد;بامداد;بامین;بامشاد;بردیا;بزرگمهر;به‌آیین;بهبد;بهرام;بهمن;بهمنش;بیژن;بهروز;بهراد;بهرنگ;بهزاد;بهداد;بهشاد;بهنام; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبراهامیان;آتشی;آجمیان;آجودانی;آخوند;آخوندی;آدامیان;آدلر;آراکلیان;آربر;آرزومانیان;آرشاکیان;آرمن;آرمین;آزاده;آزادی‌ور;آشتیانی;آصلانیان;آغداشلو;آقاجانیان;آلوسی;آنانیان;آواکیان;آوانسیان;آودیسیان;آهارونیان;آیوز;ابوالقاسمی;ابوترابی‌فرد;احمدی;احمری;اردبیلی;اروه;استپانیان;استکی;اسطرلابی;اسعردی;اشبروک;اشتراوس;اشکوری;اصفهانی;افتخاری;افخمی;اقبالی;اکبر;الباکیان;اللهیاری;الهام;الهی;امامی;امیری;امیریان;امینی;انصاری;اوپنهایمر;اولریش;اوهانیان;ایمانی;باباجانیان;بابایان;باتمانقلیچ;باتوانی;باجو;بادالیان;بارت;بارسقیان;بارک‌زا [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaliyah; Aaron; Abagail; Abbey; Abbie; Abbigail; Abby; Abdiel; Abdul; Abdullah; Abe; Abel; Abelardo; Abigail; Abigale; Abigayle; Abner; Abraham; Ada; Adah; Adalberto; Adaline; Adam; Adan; Addie; Addison; Adela; Adelbert; Adele; Adelia; Adeline; Adell; Adella; Adelle; Aditya; Adolf; Adolfo; Adolph; Adolphus; Adonis; Adrain; Adrian; Adriana; Adrianna; Adriel; Adrien; Adrienne; Afton; Aglae; Agnes; Agustin; Agustina; Ahmad; Ahmed; Aida; Aidan; Aiden; Aileen; Aimee; Aisha; Aiyana; Akeem; Al; Alaina; Alan; Alana [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LatinFirstName {
            get {
                return ResourceManager.GetString("LatinFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott; Abernathy; Abshire; Adams; Altenwerth; Anderson; Ankunding; Armstrong; Auer; Aufderhar; Bahringer; Bailey; Balistreri; Barrows; Bartell; Bartoletti; Barton; Bashirian; Batz; Bauch; Baumbach; Bayer; Beahan; Beatty; Bechtelar; Becker; Bednar; Beer; Beier; Berge; Bergnaum; Bergstrom; Bernhard; Bernier; Bins; Blanda; Blick; Block; Bode; Boehm; Bogan; Bogisich; Borer; Bosco; Botsford; Boyer; Boyle; Bradtke; Brakus; Braun; Breitenberg; Brekke; Brown; Bruen; Buckridge; Carroll; Carter; Cartwright; Casper;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LatinLastName {
            get {
                return ResourceManager.GetString("LatinLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا;خانم;دکتر;مهندس;.
        /// </summary>
        public static string PreFix {
            get {
                return ResourceManager.GetString("PreFix", resourceCulture);
            }
        }
    }
}
